### ISSUE TITLE
Instructor view seems to use wrong cubemap

### ISSUE THREAD

**Issue by gilbertohasnofb** [viktorradnai/flightgear-ask21#101] opened 2017-03-14 22:48 UTC
Back seat seems to be using the front shadow cubemap

**Comment by viktorradnai** [comment] 2017-03-14 23:02
Is #87 caused by this?

**Comment by gilbertohasnofb** [comment] 2017-03-14 23:21
@viktorradnai Hmm I see them fine here: 

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/23926598/4c8b795c-0915-11e7-957d-cfd50b8be7ec.png)

How are you changing to the instructors' seat? I hit Shift+V two or three times to cycle back and there are shadows there.

**Comment by viktorradnai** [comment] 2017-03-14 23:34
Actually the problem is that the shadows in the front and rear cockpit are done using separate maps
 and this is noticable in the footwell.
![fgfs-screen-302](https://cloud.githubusercontent.com/assets/4738178/23926901/c1cdfc3c-090e-11e7-85a8-81c83c7693a5.png)

**Comment by ghost** [comment] 2017-03-16 15:06
1. they use different maps because the situation and viewpoint is rather different, this should be no problem.
2. I just discovered that it indeed is using the wrong cubemap, a typo, will add this to #107

**Comment by ghost** [comment] 2017-03-16 15:07
Maybe irradiance maps http://wiki.flightgear.org/ALS_technical_notes#Irradiance_maps can help for the fuselage? I never found out how to use them exactly but it seems the right way..

**Comment by gilbertohasnofb** [comment] 2017-03-16 23:50
@D-ECHO I believe the c172p makes use of the irradiance effect, take a look at there. Perhaps drop a message to @wlbragg if you have concrete questions, as he is the one who implemented it in that other project.

**Comment by ghost** [comment] 2017-03-19 07:45
I tried the irradiance map (also in c172p) but I don't think it looks that good...
However, I'd close this issue as the wrong cubemap is solved

**Closed as completed by ghost** 2017-03-19 07:45 UTC
Labels: bug, lowpriority
